### PR TITLE
Add .sln and update csproj files for packaging

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
This change adds a .sln file with links to each project. This will simplify the build process as dotnet cli commands can now be run from the project root, instead of in each project directory.

I've also updated the two projects that produce nuget packages (Honeycomb & Honeycomb.AspNetCore) to consolidate the .nuspec files into the csproj. Each .nuget package will also use the honeycomb.png image as the package image.

I also updated the Test and Sample projects to netcoreapp5.0 apps.

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
Testing is still currently a WIP in PR #22.

**Comment by vreynolds** [comment]
@MikeGoldsmith looks good, I can rebase & fix #22 once this is merged. Can you add some quick start commands (`test` and `build` perhaps) in README for the rest of us dotnet nooobs? 😄

**Comment by MikeGoldsmith** [comment]
@vreynolds I've added build/test instructions and project requirements 👍

**Review by vreynolds — APPROVED** [review]
🎉

**Pull request merged**
